[package]
name = "tfhe-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "*", features = ["boolean", "shortint", "integer", "aarch64-unix"] }

[[example]]
name = "run"
path = "src/example/run.rs"